name: hrv-diffusion
channels:
  - defaults
dependencies:
  - python=3.12.2
  - pip
  - pip:
    - torch==2.3.1
    - diffusers[torch] 
    - transformers
    - opencv-python==4.10.0.84
    - ipywidgets==8.1.3
    - imageio==2.34.2
    - pandas==2.2.2
    - torchvision==0.18.1
    - bitsandbytes==0.43.1
    - matplotlib==3.9.2
    - ipywidgets
    - open_clip_torch
    - invisible_watermark